INSERT INTO roles(name) VALUES('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_PORTER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_STUDENT')ON CONFLICT DO NOTHING;
